---
apiVersion: v1 
kind: Namespace 
metadata: 
  name: deploy-ns
---
apiVersion: v1
kind: Service
metadata:
  name: deployment
  namespace: deploy-ns
spec:
  selector:
    app: kubia
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
