---
apiVersion: v1
kind: Namespace
metadata:
  name: demo-ns
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx
  namespace: demo-ns

data:
  # Adding new entries here will make them appear as files in the deployment.
  # Please update k8s.io/k8s.io/README.md when you update this file
  nginx.conf: |
    worker_processes auto;
    events {
    }

    http {
      server {
        listen 80 ;
        location = /_healthz {
          add_header Content-Type text/plain;
          return 200 'ok';
        }
        location / {
          add_header Content-Type text/plain;
          return 200 'Hello World!<br/>';
        }
      }
    }


---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: demo-ns
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      volumes:
      - name: nginx-volume
        configMap:
          name: nginx
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: nginx-volume
          mountPath: /etc/nginx
          readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: demo-ns
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
