---
apiVersion: v1 
kind: Namespace 
metadata: 
  name: demo-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: demo-ns
  labels:
    app: nginx
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
      tolerations:
      - key: "app"
        operator: "Equal"
        value: blue
        effect: NoSchedule
      nodeSelector:
        app: blue
