---
apiVersion: v1
kind: Namespace
metadata:
  name: demo-ns
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-dynamic-nfs
  namespace: demo-ns
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 16Gi
