---
apiVersion: v1
kind: Namespace
metadata:
  name: demo-ns
---
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-limit-range
  namespace: demo-ns
spec:
  limits:
  - default:
      cpu: 0.5
    defaultRequest:
      cpu: 0.25
    type: Container
